### Configuration file ###
# Warning!
# Do not change arguments with ANNOTATION_* 

# Prokka
prokka: prokka --outdir ANNOTATION_OUT --cpus 20 ANNOTATION_FAS --centre X --locustag X
perl5lib: /mibi/users/russel/Software/miniconda2/envs/annotate/lib/perl5/site_perl/5.22.0

# KOfam scan
kofam: /mibi/users/russel/Software/kofam/exec_annotation --cpu=20 -o ANNOTATION_OUT --tmp-dir ANNOTATION_TMP ANNOTATION_FAS

# dbCAN2
dbcan: python /mibi/users/russel/Software/run_dbcan/run_dbcan.py --out_dir ANNOTATION_OUT --db_dir /mibi/users/russel/Databases/dbcan2 -c ANNOTATION_GFF ANNOTATION_FAS protein --dia_cpu 20 --hmm_cpu 20

# eggNOG
eggnog: python2 /mibi/users/russel/Software/eggnog-mapper/emapper.py --cpu 20 -m diamond --data_dir /mibi/users/russel/Databases/eggnog --dmnd_db /mibi/users/russel/Databases/eggnog/eggnog_proteins.dmnd --output_dir ANNOTATION_OUT --temp_dir ANNOTATION_TMP -i ANNOTATION_FAS -o annotation

# MEROPS
merops: diamond blastp -p 20 --more-sensitive -d /mibi/users/russel/Databases/merops/merops -q ANNOTATION_FAS -o ANNOTATION_OUT

# signalp
signalp: /mibi/users/russel/Software/signalp-5.0/bin/signalp -fasta ANNOTATION_FAS -org ANNOTATION_ORG -prefix ANNOTATION_OUT -tmp ANNOTATION_TMP

# antiSMASH
antismash: antismash -c 20 ANNOTATION_GBK --outputfolder ANNOTATION_OUT

# RGI (CARD)
rgi: rgi main -n 20 -i ANNOTATION_FAS -o ANNOTATION_OUT -t protein --clean -a DIAMOND

# TnpPred
tnppred: hmmscan --cpu 20 --tblout ANNOTATION_OUT -o ANNOTATION_TMP /mibi/Databases/TnpPred/2019_05_06/hmmer321/TnpPred_HMM_Fix.hmm ANNOTATION_FAS
